name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install
      run: yarn install
    - name: Run Lint
      run: yarn lint:ci
    - name: Run Tests
      run: yarn test:ci
